{
 "title": "Kafka Consumer Lag (Micrometer)",
 "description": "spring-kafka metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_consumergroup_group_lag, topic)"
    }
   },
   {
    "name": "group",
    "label": "Consumer group",
    "query": {
     "query": "label_values(kafka_consumergroup_group_lag{client_id=~\"$client_id\",topic=\"$topic\"},group)"
    }
   },
   {
    "name": "client_id",
    "label": "Client id",
    "query": {
     "query": "label_values(kafka_consumergroup_group_lag{topic=\"$topic\"},client_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_consumer_connection_close_rate{client_id=~\"$client_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "current total lag (client side metrics)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"} >=0)"
    }
   ]
  },
  {
   "title": "current total lag (lag exporter metrics)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_consumergroup_group_topic_sum_lag{topic=\"$topic\",group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Lag per partition (client side metrics)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(kafka_consumer_fetch_manager_records_lag >= 0) + on (client_id, partition) group_left(consumer_id) (0 * kafka_consumergroup_group_lag >=0)",
     "legendFormat": "Partition {{partition}} | {{consumer_id}}"
    }
   ]
  },
  {
   "title": "Lag per partition (lag exporter metrics)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_group_lag{topic=\"$topic\",client_id=~\"$client_id\",group=\"$group\"}>=0",
     "legendFormat": "Partition {{partition}} | {{consumer_id}}"
    }
   ]
  },
  {
   "title": "Lag per partition - Topic [$topic] , ConsumerGroup [$group]",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max by (topic,partition,member_host,consumer_id) (kafka_consumergroup_group_offset{topic=\"$topic\",group=\"$group\"})"
    },
    {
     "expr": "max by (topic,partition,member_host,consumer_id) (kafka_consumergroup_group_lag{topic=\"$topic\",group=\"$group\"})"
    },
    {
     "expr": "max by (topic,partition,member_host,consumer_id) (kafka_consumergroup_group_lag_seconds{topic=\"$topic\",group=\"$group\"})"
    }
   ]
  }
 ]
}