logging:
  pattern:
    # https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#log-pattern
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"